version: "3.9"
services:
  web:
    image: hello-spring-boot-docker
    ports:
      - "8081:8080"
  firefox:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
  test:
    image: test
    depends_on:
      - web
      - firefox